# Generated by Django 5.1.3 on 2024-12-07 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contect',
            new_name='content',
        ),
    ]
