from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import PostViewSet, CommentViewSet, FeedView
from . import views

# Create a router and register the viewsets
router = DefaultRouter()
router.register(r'posts', PostViewSet, basename='post')
router.register(r'comments', CommentViewSet, basename='comment')

# Include the router-generated URLs in urlpatterns
urlpatterns = [
    path('', include(router.urls)),  # Includes all the routes generated by the router
    path('feed/', FeedView.as_view(), name='feed'),
    path('/posts/<int:pk>/like/', views.like_post, name='like_post'),
    path('/posts/<int:pk>/unlike/', views.unlike_post, name='unlike_post'),

]